# Generated by Django 5.1 on 2025-12-06 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_alter_evento_data_fim_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='eventos_app.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.participante')),
            ],
            options={
                'unique_together': {('participante', 'evento')},
            },
        ),
    ]
